fail_fast: true

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-check
        args: [--select, I, --fix]
      - id: ruff-format
  - repo: https://github.com/python-poetry/poetry
    rev: 2.2.0
    hooks:
      - id: poetry-check
        stages: [pre-push]
      - id: poetry-lock
        stages: [pre-push]
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.4.1
    hooks:
      - id: pip-compile
        args: [--upgrade]
        stages: [pre-push]
