fail_fast: true

repos:
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.13.0
    hooks:
    -   id: reorder-python-imports
        stages: [commit]
-   repo: https://git.io-warnemuende.de/michels/my-hooks
    rev: 0.0.7
    hooks:
    -   id: black-formatter
        stages: [commit]
    -   id: export-requirements
        stages: [push]
    -   id: poetry-version-bump
        stages: [commit]
    -   id: git-tag-bump
        stages: [commit]
      #     -   id: poetry-build
      #         stages: [push]
      #     -   id: upload-package
      #         stages: [push]
      #     -   id: update-sphinx-doc
      #         stages: [push]
