# base configuration for the software internals and system specifics which are
# usually set only once during the software installation process
platforms = ['CTD', 'Scanfish']
last_platform = "CTD"
seasave_exe = "C:\\Program Files (x86)\\Sea-Bird\\SeasaveV7\\Seasave.exe"
processing_exes = "C:\\Program Files (x86)\\Sea-Bird\\SBEDataProcessing-Win32"
number_of_bottles = 13

[dship]
ip='192.168.236.60'
# timeout between individual API calls in seconds
fetch_intervall = 1

    # the internal dship names of the different parameters
    [dship.identifier]
    Cruise = 'SYS.DISP.ExpNumber'
    Station = 'ActionLog.PUP.DopName'
    GPS_Time = 'SYS.DISP.TimeTxt'
    GPS_Lat = 'SYS.STR.PosLat'
    GPS_Lon = 'SYS.STR.PosLon'
    Echo_Depth = 'SYS.CALC.WaterDepth'
    Air_Pressure = 'Weatherstation_DWD.PEUMA.Air_pressure'
    Pos_Alias = 'Web.PUP.NextWPName'

[operators]
op1 = "Martin Sass"
op2 = "Sebastian Neubert"
op3 = "Julia Wickenhaeuser"
op4 = ""
op5 = ""
last = "Julia Wickenhaeuser"

[ctd]

    [ctd.paths]
    seasave_psa = "D:\\mig\\tests\\data\\Seasave_test.psa"
    output_directory = "D:\\mig\\tests\\data\\out"
    xmlcon = "D:\\mig\\tests\\data\\EMB295_003-01_CTD_0003.XMLCON"
    batch_path = "D:\\mig\\tests\\data\\processing_batch.bat"
    psa_directory = "D:\\mig\\tests\\data\\psas"

    [ctd.memory]
    last_cast = 13
    last_filename = "D:\\mig\\tests\\data\\out\\48_2_CTD_0013.hex"

[scanfish]

    [scanfish.paths]
    seasave_psa = "D:\\mig\\tests\\data\\scanfish.psa"
    output_directory = "D:\\mig\\tests\\data"
    xmlcon = "D:\\mig\\tests\\data\\EMB295_003-01_CTD_0003.XMLCON"
    batch_path = "D:\\mig\\tests\\data\\processing_batch.bat"
    psa_directory = "D:\\mig\\tests\\data\\psas"

    [scanfish.memory]
    last_cast = 11
    last_filename = "D:\\mig\\tests\\data\\83_7_SF_0011.hex"
