# base configuration for the software internals and system specifics which are
# usually set only once during the software installation process
platforms = ['CTD']
last_platform = "CTD"
seasave_exe = "C:\\Program Files (x86)\\Sea-Bird\\SeasaveV7\\Seasave.exe"
number_of_bottles = 13
downcast_option = false
self_updating = true
server_address = "http://localhost:8000/"
use_dship_values = false

[dship]
ip='dship1'
# timeout between individual API calls in seconds
fetch_intervall = 1

    # the internal dship names of the different parameters
    [dship.identifier]
    Cruise = 'SYS.DISP.ExpNumber'
    Station = 'ActionLog.PUP.DopName'
    GPS_Time = 'SYS.DISP.TimeTxt'
    GPS_Lat = 'SYS.STR.PosLat'
    GPS_Lon = 'SYS.STR.PosLon'
    Echo_Depth = 'SYS.CALC.WaterDepth'
    Air_Pressure = 'Weatherstation.PEUMA.Air_pressure'
    Pos_Alias = 'Web.PUP.NextWPName'
    Dev_Short_Name = 'ActionLog.PUP.DeviveShortName'

[operators]
op1 = ""
op2 = ""
op3 = ""
op4 = ""
op5 = ""
last = ""

[ctd]

    [ctd.paths]
    seasave_psa = ""
    output_directory = ""
    xmlcon = ""

    [ctd.memory]
    last_cast = 0
    last_filename = ""
    last_processing_file = ""
