# base configuration for the software internals and system specifics which are
# usually set only once during the software installation process
platforms = ['CTD', 'Scanfish']
last_platform = "Scanfish"
seasave_exe = "/home/emil/scripts/echo"
number_of_bottles = 13
downcast_option = false

[dship]
ip='192.168.236.60'
# timeout between individual API calls in seconds
fetch_intervall = 1

    # the internal dship names of the different parameters
    [dship.identifier]
    Cruise = 'SYS.DISP.ExpNumber'
    Station = 'ActionLog.PUP.DopName'
    GPS_Time = 'SYS.DISP.TimeTxt'
    GPS_Lat = 'SYS.STR.PosLat'
    GPS_Lon = 'SYS.STR.PosLon'
    Echo_Depth = 'SYS.CALC.WaterDepth'
    Air_Pressure = 'Weatherstation_DWD.PEUMA.Air_pressure'
    Pos_Alias = 'Web.PUP.NextWPName'

[operators]
op1 = "Martin Sass"
op2 = "Sebastian Neubert"
op3 = "Julia Wickenhaeuser"
op4 = ""
op5 = ""
last = "Martin Sass"

[ctd]

    [ctd.paths]
    seasave_psa = "/home/emil/Projects/CTD-Client/tests/data/Seasave_test.psa"
    output_directory = "/home/emil/Projects/CTD-Client/tests"
    xmlcon = "/home/emil/Projects/CTD-Client/tests/data/EMB295_003-01_CTD_0003.XMLCON"

    [ctd.memory]
    last_cast = 100
    last_filename = "/home/emil/Projects/CTD-Client/tests/data/48_62_CTD_0100.hex"
    last_processing_file = ""

[scanfish]

    [scanfish.paths]
    seasave_psa = "/home/emil/Projects/CTD-Client/tests/data/scanfish.psa"
    output_directory = "/home/emil/Projects/CTD-Client/tests/data/out"
    xmlcon = "/home/emil/Projects/CTD-Client/tests/data/EMB356_011-01_CTD_0010.XMLCON"

    [scanfish.memory]
    last_cast = 11
    last_filename = "/home/emil/Projects/CTD-Client/tests/data/out/61_96_SF_0011.hex"
    last_processing_file = "/home/emil/Projects/CTD-Client/templates/emb_basic.toml"
