version = "0.2.0"
# base configuration for the software internals and system specifics which are
# usually set only once during the software installation process
platforms = ['CTD', 'pCTD', 'sfCTD']
number_of_bottles = 13

[paths]
seasave_exe = "/home/emil/scripts/echo"
processing_exes = ""

[dship]
ip='192.168.236.60'
# timeout between individual API calls in seconds
fetch_intervall = 1

    [dship.identifier]
    Cruise = 'SYS.DISP.ExpNumber'
    Station = 'ActionLog.PUP.DopName'
    GPS_Time = 'SYS.DISP.TimeTxt'
    GPS_Lat = 'SYS.STR.PosLat'
    GPS_Lon = 'SYS.STR.PosLon'
    Echo_Depth = 'SYS.CALC.WaterDepth'
    Air_Pressure = 'Weatherstation_DWD.PEUMA.Air_pressure'
    Pos_Alias = 'Web.PUP.NextWPName'

[history]
last_cast = 10
last_filename = "/home/emil/Projects/CTD-Client/tests/data/72_71_CTD_0010.hex"
last_platform = "sfCTD"

# configuration that can be changed via the software interface by any operator
[user]

    [user.paths]
    output_directory = "/home/emil/Projects/CTD-Client/tests/data"
    xmlcon = "/home/emil/Projects/CTD-Client/tests/data/EMB295_003-01_CTD_0003.XMLCON"
    seasave_psa = "/home/emil/Projects/CTD-Client/tests/data/Seasave_test.psa"

    [user.processing]
    # one of Own, Canadian or WindowsBatch
    type = "windowsbatch"
    batch_path = "/home/emil/scripts/echo"
    psa_directory = "."
    # the processing modules that were used in the last run
    modules = ["DatCnv", "AirPressure", "WildEdit", "W_Filter", "AlignCTD", "CellTM", "Derive", "BinAvg"]

    [user.operators]
    op1 = "Heene"
    op2 = "Kolbe"
    op3 = "Faber"
    op4 = "Ruickoldt"
    op5 = "Michels"
    op6 = "Koehn"
    op7 = "Mars"
    last = "Heene"
