# base configuration for the software internals and system specifics which are
# usually set only once during the software installation process
[paths]
seasave_exe = ""
data_archive = ""
backup_location = ""

[dship]
ip='192.168.236.60'
udp_port=5558
# timeout between individual API calls in seconds
fetch_intervall = 1

    [dship.identifier]
    # Toralfs ini values
#     expedition_name='SYS.DISP.ExpName'
#     expedition_number='SYS.DISP.ExpNumber'
#     station_number='ActionLog.PUP.DopName'
#     datetime='SYS.DISP.TimeTxt'
#     timestamp='SYS.CALC.Timestamp'
#     latitude='SYS.STR.PosLat'
#     longitude='SYS.STR.PosLon'
#     echodepth='SYS.CALC.WaterDepth'
#     airpressure='Weatherstation_DWD.PEUMA.Air_pressure'
#     deviceshortname='ActionLog.PUP.DevShortname'
    # cnv metadata header values
    #Cruise = 'ActionLog.PUP.ExpNumber'
    Station = 'ActionLog.PUP.DopName'
    Platform = 'Web.PUP.NextWPName'
    # Cast = ''
    # Operator = ''
    GPS_Time = 'SYS.DISP.TimeTxt'
    GPS_Lat = 'SYS.STR.PosLat'
    GPS_Lon = 'SYS.STR.PosLon'
    Echo_Depth = 'SYS.CALC.WaterDepth'
    Air_Pressure = 'Weatherstation_DWD.PEUMA.Air_pressure'
#WsStartID = 'ActionLog.PUP.Scientist'
    # Pos_Alias = 'Web.PUP.NextWPName'

[history]
last_cast = 0
last_filename = ""

[operators]
op1 = "Heene"
op2 = "Kolbe"
op3 = "Faber"
op4 = "Ruickoldt"
op5 = "Michels"
op6 = "Koehn"
op7 = "Mars"
last = "Michels"

# configuration that can be changed via the software interface by any operator
[user]
number_of_bottles = 13

    [user.bottle_layout]
    1 = 1
    2 = 2
    3 = 3
    4 = 4
    5 = 5
    6 = 6
    7 = 7
    8 = 8
    9 = 9
    10 = 10
    11 = 11
    12 = 12
    13 = 13

    [user.paths]
    xmlcon = "/home/emil/Projects/CTD-Client/tests/data/EMB295_003-01_CTD_0003.XMLCON"
    export_location = ""
    psa = "/home/emil/Projects/CTD-Client/tests/data/Seasave_test.psa"
    hex = ""

    [user.processing]
    batch = true
    modules = ["DatCnv", "AirPressure", "WildEdit", "W_Filter", "AlignCTD", "CellTM", "Derive", "BinAvg"]
    processing_exes = ""
    psas = ""
