# base configuration for the software internals and system specifics which are
# usually set only once during the software installation process

platforms = ['CTD', 'pCTD', 'sfCTD']

[paths]
seasave_exe = "C:\\Program Files (x86)\\Sea-Bird\\SeasaveV7\\Seasave.exe"
data_archive = "D:\\mig\\tests\\data\\out"
backup_location = ""

[dship]
ip='192.168.236.60'
udp_port=5558
# timeout between individual API calls in seconds
fetch_intervall = 1

    [dship.identifier]
    # cnv metadata header values
    # Cruise = ''
    Station = 'ActionLog.PUP.DopName'
    # Platform = ''
    # Cast = ''
    # Operator = ''
    GPS_Time = 'SYS.DISP.TimeTxt'
    GPS_Lat = 'SYS.STR.PosLat'
    GPS_Lon = 'SYS.STR.PosLon'
    Echo_Depth = 'SYS.CALC.WaterDepth'
    Air_Pressure = 'Weatherstation_DWD.PEUMA.Air_pressure'
    # WsStartID = ''
    Pos_Alias = 'Web.PUP.NextWPName'

[history]
last_cast = 0
last_filename = ''
last_platform = "CTD"

[operators]
op1 = "Heene"
op2 = "Kolbe"
op3 = "Faber"
op4 = "Ruickoldt"
op5 = "Michels"
op6 = "Koehn"
op7 = "Mars"
last = "Michels"

# configuration that can be changed via the software interface by any operator
[user]
number_of_bottles = 13

    [user.bottle_layout]
    1 = 1
    2 = 2
    3 = 3
    4 = 4
    5 = 5
    6 = 6
    7 = 7
    8 = 8
    9 = 9
    10 = 10
    11 = 11
    12 = 12
    13 = 13

    [user.paths]
    xmlcon = "D:\\mig\\tests\\data\\EMB295_003-01_CTD_0003.XMLCON"
    export_location = "D:\\mig\\tests\\data\\out"
    psa = "D:\\mig\\tests\\data\\Seasave_test.psa"
    hex = "D:\\mig\\tests\\data\\EMB295_003-01_CTD_0003.hex"

    [user.processing]
    batch = true
    modules = ["DatCnv", "AirPressure", "WildEdit", "W_Filter", "AlignCTD", "CellTM", "Derive", "BinAvg"]
    processing_exes = "C:\\Program Files (x86)\\Sea-Bird\\SBEDataProcessing-Win32"
    psas = "D:\\mig\\tests\\data\\psas"
