#!/bin/bash

# if argument given, use that as version string
if [[ $# -gt 0 ]]; then
    export VERSION="$1"
# otherwise, get the latest git tag
else
    VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
fi

cat <<EOF >src/ctdclient/version.py
# This file is auto-generated by write_version.sh during build
__version__ = "$VERSION"
EOF

echo "Version set to $VERSION"
