name: Publish package

on:
  push:
    branches:
      - main
jobs:
  version_bump:
    runs-on: ubuntu-latest
    container:
      volumes:
        - htmls:/htmls
    outputs:
      bump_level: ${{ steps.bump_level.outputs.BUMP_LEVEL }}
      new_version: ${{ steps.new_version.outputs.NEW_VERSION }}
      pr_desc: ${{ steps.pr_desc.outputs.PR_DESC }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git User
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global credential.helper store
          echo "https://${{ secrets.GIT_USER_NAME }}:${{ secrets.GIT_TOKEN }}@git.io-warnemuende.de" > ~/.git-credentials
          chmod 600 ~/.git-credentials

      - name: Get PR Description from Gitea API
        id: pr_desc
        run: |
          PR_NUMBER=$(git log -1 --pretty=%B | grep -oP '\(#\d+\)' | grep -oP '\d+')
          PR_DESC=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
                     "https://git.io-warnemuende.de/api/v1/repos/${{ gitea.repository }}/pulls/$PR_NUMBER" | jq -r '.title')
          echo "PR_DESC=$PR_DESC" >> $GITHUB_ENV
          echo "PR_DESC=$PR_DESC" >> $GITHUB_OUTPUT

      - name: Determine Version Bump Level
        id: bump_level
        run: |
          if echo "$PR_DESC" | grep -iq "#major"; then
            VERSION_BUMP="major"
          elif echo "$PR_DESC" | grep -iq "#minor"; then
            VERSION_BUMP="minor"
          else
            VERSION_BUMP="patch"
          fi
          echo "VERSION_BUMP=$VERSION_BUMP" >> $GITHUB_ENV
          echo "BUMP_LEVEL=$VERSION_BUMP" >> $GITHUB_OUTPUT

      - name: Bump Version Based on PR Description
        id: new_version
        run: |
          git fetch --tags origin
          CURRENT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Current Tag: $CURRENT_TAG"

          if [[ ${CURRENT_TAG::1} == "v" ]] ; then
            CURRENT_TAG="${CURRENT_TAG:1}"
          fi

          MAJOR=$(echo $CURRENT_TAG | cut -d '.' -f 1)
          MINOR=$(echo $CURRENT_TAG | cut -d '.' -f 2)
          PATCH=$(echo $CURRENT_TAG | cut -d '.' -f 3)

          case $VERSION_BUMP in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch)
              PATCH=$((PATCH + 1))
              ;;
          esac

          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo $NEW_VERSION
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create and Push Git Tag
        run: |
          git tag $NEW_VERSION
          git push origin $NEW_VERSION --no-verify

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Update documentation
        run: |
          pip install -r requirements.txt
          pip install sphinx sphinx-autodoc-typehints myst-parser furo
          sphinx-apidoc -f -e -o docs/source src/ctdclient
          sphinx-build -b html docs/source /htmls

      - name: Checkout pages branch
        run: |
          git fetch
          git checkout pages

      - name: Update pages branch
        continue-on-error: true
        run: |
          rm -rf *
          cp -r /htmls/* .
          git add .
          git commit -m "Update Sphinx documentation" --no-verify
          git push -u origin pages



  build_binary:
    needs: version_bump
    container:
      image: batonogov/pyinstaller-windows:v4.11.1
    env:
      NEW_VERSION: ${{ needs.version_bump.outputs.new_version }}
      PR_DESC: ${{ needs.version_bump.outputs.pr_desc }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    steps:
      - name: Install missing dependencies
        run: apt update && apt install -y nodejs curl git jq

      - uses: actions/checkout@v3

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip download gsw==3.6.19 --platform win_amd64 --python-version 3.12 --only-binary :all:
          mv gsw-3.6.19-cp312-cp312-win_amd64.whl gsw-3.6.19-cp313-cp313-win_amd64.whl
          pip install gsw-3.6.19-cp313-cp313-win_amd64.whl
          pip install -r requirements.txt

      - name: Build Windows binary
        run: |
          git fetch
          git branch -f pages origin/pages
          git checkout pages :
          mkdir /htmls
          cp -r -t /htmls *.html *.inv *.js _static _sources _images
          ./write_version.sh $NEW_VERSION
          pyinstaller -y windows.spec

      - name: Create Gitea release
        run: |
          RESPONSE=$(curl -X 'POST' \
            "https://git.io-warnemuende.de/api/v1/repos/CTD-Software/CTD-Client/releases" \
            -H "Authorization: token $GIT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"$PR_DESC\", \"name\": \"Release $NEW_VERSION\", \"tag_name\": \"$NEW_VERSION\"}")
          echo $RESPONSE
          RELEASE_ID=$(echo "$RESPONSE" | jq -r '.id')
          echo "RELEASE_ID=$RELEASE_ID" >> $GITHUB_ENV

      - name: Upload binary to release
        run: |
          curl -X 'POST' \
            "https://git.io-warnemuende.de/api/v1/repos/CTD-Software/CTD-Client/releases/$RELEASE_ID/assets?=ctdclient.exe" \
            -H "Authorization: token $GIT_TOKEN" \
            -H 'accept: application/json' \
            -H 'Content-Type: multipart/form-data' \
            -F 'attachment=@dist/ctdclient.exe'

