name: Run tests and check format

on:
  pull_request:
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - uses: astral-sh/ruff-action@v3

      - name: Check formatting
        run: ruff check

      - name: Set up uv
        uses: astral-sh/setup-uv@v7.3.1
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --extra test

      - name: Run tests
        run: uv run pytest
