input = [""]
psa_directory = ""

[modules.datcnv]
psa = "DatCnv.psa"

[modules.airpressure]

[modules.wildedit_geomar]

[modules.w_filter]
psa = "W_Filter.psa"

[modules.alignctd]
Oxygen = "3"

[modules.celltm]
psa = "CellTM.psa"

[modules.derive]
psa = "Derive.psa"

[modules.bottlesum]
psa = "BottleSum.psa"

[modules.create_bottle_file]

[modules.binavg_1]
psa = "BinAvg_1.psa"
file_suffix = "_1m"

[modules.binavg_2]
psa = "BinAvg_2.psa"
file_suffix = "_25cm"

[modules.binavg_3]
psa = "BinAvg_3.psa"
file_suffix = "_1second"
