exe_directory = "/home/emil/.wine/drive_c/Program Files (x86)/Sea-Bird/SBEDataProcessing-Win32/"
psa_directory = "/home/emil/Projects/CTD-Client/tests/data/psas/EMB356/"
output_directory = "/home/emil/Projects/CTD-Client/tests/data/out"

[modules]
[modules.datcnv]
psa = "DatCnv.psa"

[modules.airpressure]
psa = "AirPressure.par"

[modules.w_filter]
psa = "W_Filter.psa"

[modules.alignctd]
psa = "AlignCTD.psa"

[modules.celltm]
psa = "CellTM.psa"

[modules.derive]
psa = "Derive.psa"

[modules.binavg]
psa = "BinAvg_1.psa"
