exe_directory = "C:\\Program Files (x86)\\Sea-Bird\\SBEDataProcessing-Win32"
psa_directory = ""
file_list = []

[optional]
output_directory = ""
file_type_directory = ""
new_file_name = ""
file_suffix = ""

[modules]
[modules.datcnv]
psa = "DatCnv.psa"

[modules.wildedit]
psa = "WildEdit.psa"

[modules.w_filter]
psa = "W_Filter.psa"

[modules.alignctd]
psa = "AlignCTD.psa"

[modules.celltm]
psa = "CellTM.psa"

[modules.derive]
psa = "Derive.psa"

[modules.bottlesum]
psa = "BottleSum.psa"

[modules.binavg]
psa = "BinAvg_1.psa"
