# for all arguments inside this configuration file it is advised to use
# absolute file paths (starting with C: or the likes)

# arguments that are strictly necessary
exe_directory = '/home/emil/.wine/drive_c/Program Files (x86)/Sea-Bird/SBEDataProcessing-Win32/'
psa_directory = "tests/data/psas"

# at least one of the following two arguments needs to be set
file_list = []
input_directory = 'tests/data'

# if the xmlcons do not reside inside the same directory as the hex files, you
# need to specify a file path to an XMLCON directory that works for all the
# hex files in the file list or input_dir
xmlcons = ''

# non mandatory arguments for control of the output
# if nothing is set, the input directories and file names are used
output_directory = 'tests/data/out'
new_file_name = ''
file_suffix = ''

# a list of processing modules with their respective psas
# if none given, searches for the best match inside psa_dir
[modules]

[modules.datcnv]

[modules.w_filter]

[modules.celltm]

[modules.alignctd]

[modules.binavg]
