input = [""]
output_type = "cnv"
# output_dir = ""
# output_name = ""

# these paths need to be altered to real targets
[modules.datcnv]
psa = "DatCnv.psa"

[modules.wildedit]
psa = "WildEdit.psa"

[modules.w_filter]
psa = "W_Filter.psa"

[modules.alignctd]
psa = "AlignCTD.psa"

[modules.celltm]
psa = "CellTM.psa"

[modules.derive]
psa = "Derive.psa"

[modules.bottlesum]
psa = "BottleSum.psa"

[modules.binavg]
psa = "BinAvg_1.psa"
